export const GET_ALL_QUATIONLIST = 'GET_ALL_QUATIONLIST';
export const GET_ALL_QUATIONDETAILS = 'GET_ALL_QUATIONDETAILS';
export const GET_CATAGORY_LIST = 'GET_CATAGORY_LIST';
export const SET_INQUIRY_CODE = 'SET_INQUIRY_CODE'
